### PR TITLE
Don't coerce version strings to semver, quote package names

### LINKED ISSUE #64: Quote packages name, when calling npm
Hi, you need to quote packages names, when you calling package manager.
For example, if peer deps is specified like ```"package": ">=1.2.3"```
then you will call npm to install deps like:
```npm i package@>=1.2.3```,  that produces stdout redirect to the file ```=1.2.3```

### LINKED ISSUE #71: Incorrect selection of package version
I have an `eslint-config-myconfig` package in a private registry having the following peer dependencies:

```json
  "peerDependencies": {
    "@typescript-eslint/eslint-plugin": ">=2.21 <3",
    "@typescript-eslint/parser": ">=2.21 <3",
    "eslint": ">=6.8 <7",
    "eslint-config-airbnb-typescript": ">=7 <8",
    "eslint-config-prettier": ">=6.10 <7",
    "eslint-plugin-import": ">=2.20 <3",
    "eslint-plugin-prettier": ">=3.1 <4",
    "eslint-plugin-security": ">=1.4 <2",
    "prettier": ">=1.19 <2",
    "typescript": ">=3.8 <4"
  },
```

When I run `install-peerdeps`, I'm getting a "no matching version" error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@3.8.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

It appears that install-peerdeps is not using the exact same semver expression when issuing the "npm install" command. So, instead of **`npm install typescript@">=3.8 <4"`**, it's just reading the first literal a.b.c number.

A quick debug shows the command being executed:

```js
npm [
  'install',
  'eslint-config-insight@0.1.0',
  '@typescript-eslint/eslint-plugin@2.21.0',
  '@typescript-eslint/parser@2.21.0',
  'eslint@6.8.0',
  'eslint-config-airbnb-typescript@7.0.0',
  'eslint-config-prettier@6.10.0',
  'eslint-plugin-import@2.20.0',
  'eslint-plugin-prettier@3.1.0',
  'eslint-plugin-security@1.4.0',
  'prettier@1.19.0',
  'typescript@3.8.0',
  '--save-dev'
]
```

### PR DESCRIPTION
**Pull request by nathanhleung**
`install-peerdeps` uses the [`semver`](https://www.npmjs.com/package/semver) package to coerce peerdep versions specified in `package.json` to specific, "valid"/literal versions of the form `x.y.z` to generate the peer dependency install command. However, this coercion means that a version specified as `^7` in `peerDependencies` is coerced to `7.0.0`, which might not necessarily exist.

Instead, we should just use the version directly specified in `package.json`. Resolves #71.

Also started quoting package names to resolve #64

## Previous Behavior

```
$ npx install-peerdeps --dev @wordpress/eslint-plugin --dry-run

install-peerdeps v3.0.1
This command would have been run to install @wordpress/eslint-plugin@latest:
npm install @wordpress/eslint-plugin@8.0.1 eslint@7.0.0 --save-dev
```

## New Behavior

```
$ npx install-peerdeps --dev @wordpress/eslint-plugin --dry-run

install-peerdeps v3.0.1
This command would have been run to install @wordpress/eslint-plugin@latest:
npm install "@wordpress/eslint-plugin@8.0.1" "eslint@^7" --save-dev
```

@karlhorky could you test this branch?

@ljharb should this change be classified as a bugfix (bump semver patch version)? it changes prior behavior but should result in more flexibility rather than less (i.e. the install command will install `@^7` etc rather than `@7.0.0`)

### CODE REVIEW

File: src/install-peerdeps.js [hunk 1]
```diff
@@ -154,12 +154,9 @@ const getPackageString = ({ name, version }) => {
   if (version.indexOf(" ") >= 0) {
     // Semver ranges can have a join of comparator sets
     // e.g. '^3.0.2 || ^4.0.0' or '>=1.2.7 <1.3.0'
-    // Take each version in the range and find the maxSatisfying
-    const rangeSplit = version
-      .split(" ")
-      .map(v => coerce(v))
```
Comment (ljharb) [inline src/install-peerdeps.js:160]: it does seem important to still check range validity here? altho then i suppose dist-tags like “next” wouldn’t work.

Comment (nathanhleung) [reply src/install-peerdeps.js:160]: If the range is invalid wouldn't that be a bug in the other package? Do you know how NPM handles invalid ranges here?

Based on the [package.json docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies) on the NPM website, simply taking the last element of the range _should_ work.

Related PR: #4

Thanks for reviewing so fast and sorry for the messy diff — I think my prettier extension settings have changed since I first started writing this package. Force-pushed without the formatting so it's hopefully easier to read.

Comment (ljharb) [reply src/install-peerdeps.js:160]: Yeah i think it makes the most sense to just let the package manager handle it.

**Review by ljharb — APPROVED** [review]

**Comment by karlhorky** [comment]
> @karlhorky could you test this branch?

Sure, @uebriges and I can test today with `create-react-app`!

**Comment by karlhorky** [comment]
Yep, looks good! 🚀

```bash
$ git clone https://github.com/nathanhleung/install-peerdeps.git
$ cd install-peerdeps
$ git checkout nathanhleung-version-fix
$ yarn
$ yarn build && npx install-peerdeps --yarn --dev eslint-config-react-app  --dry-run
yarn run v1.22.5
$ npm run clean
> install-peerdeps@3.0.1 clean
> rimraf lib
$ babel src --out-dir lib --ignore *.test.js
Successfully compiled 9 files with Babel (1775ms).
:sparkles:  Done in 4.10s.
install-peerdeps v2.0.3
This command would have been run to install eslint-config-react-app@latest:
yarn add eslint-config-react-app@6.0.0 @typescript-eslint/eslint-plugin@^4.0.0 @typescript-eslint/parser@^4.0.0 babel-eslint@^10.0.0 eslint@^7.5.0 eslint-plugin-flowtype@^5.2.0 eslint-plugin-import@^2.22.0 eslint-plugin-jest@^24.0.0 eslint-plugin-jsx-a11y@^6.3.1 eslint-plugin-react@^7.20.3 eslint-plugin-react-hooks@^4.0.8 eslint-plugin-testing-library@^3.9.0 --dev --registry https://registry.npmjs.org
```

**Comment by nathanhleung** [comment]
> Yep, looks good! 🚀

Perfect, thanks!

**Comment by nathanhleung** [comment]
@karlhorky I just published and it looks like I'm getting an error. Can you try running `npx install-peerdeps eslint-config-airbnb --dev` without `--dry-run` and let me know if it works, sending me any error logs if it doesn't?

**Comment by nathanhleung** [comment]
> @karlhorky I just published and it looks like I'm getting an error. Can you try running `npx install-peerdeps eslint-config-airbnb --dev` without `--dry-run` and let me know if it works, sending me any error logs if it doesn't?

Reverted the change that added quotes around the package name for now and published a new version, 3.0.3. However, the version that wasn't working for me is still up as version 3.0.2.

**Comment by karlhorky** [comment]
Ah sorry! 🙈 I saw that you were using `--dry-run`, so I didn't end up testing it with a normal app (eg. without the `--dry-run`).

We'll try to do the full workflow with `3.0.2` - I guess if it's broken for you, then it'll be also broken for us.

**Comment by karlhorky** [comment]
`3.0.2` on macOS results in a `ERR undefined` error (related to @kirlat's #128?)

```
$ mkdir repro
$ cd repro
$ npx create-react-app .
$ npx install-peerdeps@3.0.2 eslint-config-airbnb --dev
Need to install the following packages:
  install-peerdeps@3.0.2
Ok to proceed? (y) y
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
install-peerdeps v3.0.2
It seems as if you are using Yarn. Would you like to use Yarn for the installation? (y/n) y
Installing peerdeps for eslint-config-airbnb@latest.
yarn add "eslint-config-airbnb@18.2.1" "eslint@^7.2.0" "eslint-plugin-import@^2.22.1" "eslint-plugin-jsx-a11y@^6.4.1" "eslint-plugin-react@^7.21.5" "eslint-plugin-react-hooks@^1.7.0" --dev

ERR undefined
npm ERR! code 1
npm ERR! path /Users/k/p/repro
npm ERR! command failed
npm ERR! command sh -c install-peerdeps eslint-config-airbnb --dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/k/.npm/_logs/2021-01-29T16_53_19_871Z-debug.log
```

**Comment by karlhorky** [comment]
`3.0.3` on macOS (in the same CRA project) results in successful run:

```
npx install-peerdeps@3.0.3 eslint-config-airbnb --dev
Need to install the following packages:
  install-peerdeps@3.0.3
Ok to proceed? (y) y
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
install-peerdeps v3.0.3
It seems as if you are using Yarn. Would you like to use Yarn for the installation? (y/n) y
Installing peerdeps for eslint-config-airbnb@latest.
yarn add eslint-config-airbnb@18.2.1 eslint@^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^1.7.0 --dev

SUCCESS eslint-config-airbnb
  and its peerDeps were installed successfully.
```

**Comment by karlhorky** [comment]
Running on Windows 10 now...

**Comment by karlhorky** [comment]
Ran on Windows 10 too: same result.

`3.0.2` (fails with `ERR undefined`)

```
$ npx install-peerdeps@3.0.2 eslint-config-airbnb --dev
Need to install the following packages:
  install-peerdeps@3.0.2
Ok to proceed? (y) y
npm WARN deprecated @babel/polyfill@7.12.1: :rotating_light: This package has been deprecated in favor of separate inclusion of a polyfill
 and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
install-peerdeps v3.0.2
It seems as if you are using Yarn. Would you like to use Yarn for the installation? (y/n) y
Installing peerdeps for eslint-config-airbnb@latest.
yarn add "eslint-config-airbnb@18.2.1" "eslint@^7.2.0" "eslint-plugin-import@^2.22.1" "eslint-plugin-jsx-a11y@^6.4.1" "eslint-plugin-react@^7.21.5" "eslint-plugin-react-hooks@^1.7.0" --dev
ERR undefined
npm ERR! code 1
npm ERR! path D:\upleveled-softwork\repro
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c install-peerdeps eslint-config-airbnb --dev
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joseh\AppData\Local\npm-cache\_logs\2021-01-29T17_03_07_138Z-debug.log
```

`3.0.3` (succeeds)

```
$ npx install-peerdeps@3.0.3 eslint-config-airbnb --dev
Need to install the following packages:
  install-peerdeps@3.0.3
Ok to proceed? (y) y
npm WARN deprecated @babel/polyfill@7.12.1: :rotating_light: This package has been deprecated in favor of separate inclusion of a polyfill
 and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
install-peerdeps v3.0.3
It seems as if you are using Yarn. Would you like to use Yarn for the installation? (y/n) y
Installing peerdeps for eslint-config-airbnb@latest.
yarn add eslint-config-airbnb@18.2.1 eslint@^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^1.7.0 --dev
SUCCESS eslint-config-airbnb
  and its peerDeps were installed successfully.
```

**Comment by karlhorky** [comment]
So it looks like quoting the versions is not going to be a working solution for @zdm's #64 ... at least not as they are in [`fa0b30e`](https://github.com/nathanhleung/install-peerdeps/pull/126/commits/fa0b30e5d5b5425290c0514c7f95602a7e96e054)

**Comment by nathanhleung** [comment]
Thanks for testing all this for me! Reopening #64.

**Comment by karlhorky** [comment]
Ah seems like this solution for version ranges doesn't work after all (installing the `eslint-config-react-app` peer deps in a new `create-react-app` project with `install-peerdeps@3.0.3` just failed on Windows).

**Comment by valeriirivne** [comment]
Hey, I have a a package.json file, created one with npm init. But I failed to install everything needed by the config: npx install-peerdeps --dev eslint-config-wesbos. What am I doing wrong? Thank you.
nove v15.8.0, npm v7.5.1
NPM ERR1

**Comment by nathanhleung** [comment]
Hi @valeriirivne, thanks for the report. For now, can you try copying the npm install command that was outputted?

(copy the log line that starts with `npm install` and ends with `--save-dev`)

**Comment by valeriirivne** [comment]
Hi, @nathanhleung , do you mean the output after I run the command npm install?
output
Please help, how can I solve this issue? I tried 10times and the same error after I try to install dependencies. Thank you

**Comment by karlhorky** [comment]
I think Nathan means the line in the first screenshot you posted, the line that starts with `npm install eslint-config-wesbos@1.0.1 babel-eslint@^10.1.0 ...`

**Comment by valeriirivne** [comment]
Sorry, npx install-peerdeps --dev eslint-config-wesbos. I took it from here https://github.com/wesbos/eslint-config-wesbos --- "Local / Per Project Install". I do exactly like is written there, but this bug doesn't allow me to load that dependency. Can somebody help me how can I solve that issue? Thanks

**Comment by ljharb** [comment]
@valeriirivne are you perhaps using npm 7, and perhaps you have a peer dep incompatibility?

**Comment by valeriirivne** [comment]
@ljharb  yes, npm7. Please, give a hint, how can I solve that issue and install this dependenicies? Thank you
version node

**Comment by ljharb** [comment]
It’s not related to this project - it means you already have a version of eslint, or one of those eslint plugins, that’s installed or required as a peer dep by another package, and they’re incompatible. upgrade to npm v7.5.4, and try installing the deps manually with npm, and it might give you more info.

**Comment by valeriirivne** [comment]
@ljharb  Thanks for reply. I will try like you said.
